
import { Destination } from './types';

export const DESTINATIONS: Destination[] = [
  {
    id: 'eiffel-tower',
    name: 'Eiffel Tower',
    country: 'France',
    coordinates: { x: 48, y: 35 },
    category: 'Historical',
    description: 'An iconic wrought-iron lattice tower on the Champ de Mars in Paris.',
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&q=80&w=800',
    funFact: 'The Eiffel Tower grows by up to 6 inches in the summer due to thermal expansion.',
  },
  {
    id: 'great-wall',
    name: 'Great Wall',
    country: 'China',
    coordinates: { x: 82, y: 40 },
    category: 'Historical',
    description: 'A series of fortifications that were built across the historical northern borders of ancient Chinese states.',
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=800',
    funFact: 'Contrary to popular belief, it cannot be seen from the moon with the naked eye!',
  },
  {
    id: 'pyramids-giza',
    name: 'Pyramids of Giza',
    country: 'Egypt',
    coordinates: { x: 58, y: 45 },
    category: 'Historical',
    description: 'The oldest and largest of the three pyramids in the Giza pyramid complex.',
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&q=80&w=800',
    funFact: 'They were originally covered in polished white limestone that made them shine like a star.',
  },
  {
    id: 'machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    coordinates: { x: 30, y: 65 },
    category: 'Adventure',
    description: 'A 15th-century Inca citadel located in the Eastern Cordillera of southern Peru.',
    image: 'https://images.unsplash.com/photo-1587590227264-0ac64ce63ce8?auto=format&fit=crop&q=80&w=800',
    funFact: 'No mortar was used to build the citadel. The stones are cut so precisely they fit together perfectly.',
  },
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    country: 'USA',
    coordinates: { x: 20, y: 38 },
    category: 'Nature',
    description: 'A steep-sided canyon carved by the Colorado River in Arizona, United States.',
    image: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?auto=format&fit=crop&q=80&w=800',
    funFact: 'The Grand Canyon is actually bigger than the entire state of Rhode Island.',
  },
  {
    id: 'taj-mahal',
    name: 'Taj Mahal',
    country: 'India',
    coordinates: { x: 72, y: 48 },
    category: 'Cultural',
    description: 'An ivory-white marble mausoleum on the right bank of the river Yamuna in Agra.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657451ddc?auto=format&fit=crop&q=80&w=800',
    funFact: 'The building is perfectly symmetrical from all four sides.',
  },
  {
    id: 'mount-fuji',
    name: 'Mount Fuji',
    country: 'Japan',
    coordinates: { x: 88, y: 42 },
    category: 'Nature',
    description: 'Japan’s highest mountain, an active volcano about 100 kilometers southwest of Tokyo.',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800',
    funFact: 'Mount Fuji is actually three volcanoes on top of each other.',
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Greece',
    coordinates: { x: 54, y: 42 },
    category: 'Beach',
    description: 'One of the Cyclades islands in the Aegean Sea, known for its whitewashed houses and blue domes.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=800',
    funFact: 'The island is actually what remains after an enormous volcanic eruption.',
  }
];
